FirstMVC/Controllers/BTController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FirstMVC.Models;

namespace FirstMVC.Controllers
{
    public class BTController : Controller
    {
        public IActionResult tong()
        {
            return View();
        }
        [HttpPost]
        public IActionResult tong(string hesoA, string hesoB)
        {
            double hs1 =0, hs2 =0, Tong = 0;
            string Result;
            if(!String.IsNullOrEmpty(hesoA)) hs1 = Convert.ToDouble(hesoA);
            if(!String.IsNullOrEmpty(hesoB)) hs2 = Convert.ToDouble(hesoB);
            Tong = hs1+hs2;
            Result = "Tong 2 so : " + Tong  ;
            ViewBag.Nhandulieu = Result;
            return View();
        }
        public IActionResult Giaiptb2()
        {
        return View();
        }

        [HttpPost]
        public IActionResult Giaiptb2(string hesoA, string hesoB, string hesoC)
        {
            double delta, x1, x2, a=0, b=0, c=0;
            string ketqua;
            if(!String.IsNullOrEmpty(hesoA)) a = Convert.ToDouble(hesoA);
            if(!String.IsNullOrEmpty(hesoB)) b = Convert.ToDouble(hesoB);
            if(!String.IsNullOrEmpty(hesoC)) c = Convert.ToDouble(hesoC);
            if(a==0) ketqua = "Khong phai phuong trinh bac 2";
            else{
            //tinh delta
                delta = Math.Pow(b,2) - 4*a*c;
            // Giai phuong trinh
                if(delta<0) ketqua ="Phuong trinh vo nghiem";
                else if(delta==0)
                {
                    x1 = -b/(2*a);
                    ketqua ="Phuong trinh co nghiem kep = "+ x1;
                }
                else 
                {
                    x1= (-b + Math.Sqrt(delta))/(2*a);
                    x2= (-b - Math.Sqrt(delta))/(2*a);
                    ketqua = "Phuong trinh co 2 nghiem phan biet: x1= "+ x1 + ", x2= "+x2;
                }
            }
            ViewBag.gpt = ketqua;
            return View();
        }
    }
}

FirstMVC/Controllers/DaiLyController.cs
using System.Runtime.Serialization;
using FirstMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVC.Controllers
{
    public class DaiLyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Index(DaiLy DL)
        {
            string strResult = "Xin chao : " + DL.MaDaiLy + " - " + DL.TenDaiLy +  " - " + DL.DiaChi +  " - " + DL.NguoiDaiDien +  " - " + DL.MaHTPP +  " - " + DL.NguoiDaiDien ;
            ViewBag.thongbao = strResult;
            return View();
        }
    }
}

FirstMVC/Controllers/EmployeeController.cs
using System.Runtime.Serialization;
using FirstMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVC.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Employee emp)
        {
            string strResult = "Xin Chào" + emp.MaNV + "-" + emp.TenNV + "-" + emp.Tuoi ;
            ViewBag.thongbao = strResult;
            return View();
        }
    }
}

FirstMVC/Controllers/PersonController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FirstMVC.Models;

namespace FirstMVC.Controllers;

public class PersonController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public PersonController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Index(Person ps)
    {
        string strResult = "Xin chao : " + ps.FullName + " - " + ps.PersonID  + "!" ;
        ViewBag.Nhandulieu = strResult;
        return View();
    }
}
    

FirstMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FirstMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BT" asp-action="tong">Tong</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Person</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BT" asp-action="Giaiptb2">Giaiptb2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HeThongPhanPhoi" asp-action="Index">HTPP</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DaiLy" asp-action="Index">Dai Ly</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FirstMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>